### ISSUE TITLE
Unsaved file cannot set syntax to python

### ISSUE THREAD

**Issue by QueenT** [MagicStack/MagicPython#30] opened 2015-12-29 16:24 UTC
After disable built-in python package, the View>Syntax>Python option is also gone.Thus I can't set python syntax for a new created file which is not saved.
Would you consider adding an syntax setting entry in that place?

**Comment by staticor** [comment] 2015-12-31 03:03
guess we have same puzzles, just newly to use magicpython, and set syntax to magicpython on each time edit .py files. 

is there a better way?  

env: sublime text2, and os x.

**Comment by 1st1** [comment] 2016-01-06 17:28
@QueenT Which editor are you using? 

@staticor you may want to disable standard Python syntax, or you can do View -> Syntax -> Open all with current extension as... -> MagicPython

**Comment by QueenT** [comment] 2016-01-08 04:17
Hi, @1st1 I'm using Sublime Text.

**Comment by 1st1** [comment] 2016-02-09 21:34
> guess we have same puzzles, just newly to use magicpython, and set syntax to magicpython on each time edit .py files.

Can't reproduce this :(

@QueenT Do you have the `View > Syntax > MagicPython` option?

**Comment by 1st1** [comment] 2016-06-12 21:16
Has this one been resolved?

**Comment by 1st1** [comment] 2016-12-16 22:11
Since this issue hasn't been upvoted or reported again, I'm going to close it. Likely this was a platform/environment specific bug of Sublime Text.

**Closed by 1st1** 2016-12-16 22:11 UTC
Labels: sublime editor bug
