### ISSUE TITLE
long python string causes syntax coloring to stop working

### ISSUE THREAD

**Issue by grayaii** [MagicStack/MagicPython#79] opened 2017-04-19 21:40 UTC
The color syntax stops working if a python string variable is too long.

Here is relevant version information:
* **Atom 1.16.0**:
* **MagicPython version 1.0.9**:

Screenshot of it working (string length is 999):
![works](https://cloud.githubusercontent.com/assets/847072/25203421/360a8fd2-2527-11e7-84e8-f5f5c856afb9.jpg)

Screenshot of it not working (string length is 1000):
![no_work](https://cloud.githubusercontent.com/assets/847072/25203433/4338778c-2527-11e7-9dbf-e80042fed156.jpg)

**Comment by 1st1** [comment] 2017-04-20 01:53
Interesting. I wan't able to reproduce this in 1.14, looks like something broke in 1.16 in how Atom interprets schema regexps.

**Comment by 1st1** [comment] 2017-04-20 01:59
Looks like JavaScript highlighter is also broken in 1.16:

![screen shot 2017-04-19 at 9 56 22 pm](https://cloud.githubusercontent.com/assets/239003/25209819/537b5e74-254b-11e7-8b9c-450246132e50.png)

![screen shot 2017-04-19 at 9 57 22 pm](https://cloud.githubusercontent.com/assets/239003/25209821/5630d1d0-254b-11e7-8b6c-aa64721e2149.png)

And here's how MagicPython similarly breaks for the same code:

![screen shot 2017-04-19 at 9 57 39 pm](https://cloud.githubusercontent.com/assets/239003/25209848/6baa622e-254b-11e7-8e4d-0def48b92925.png)

![screen shot 2017-04-19 at 9 57 43 pm](https://cloud.githubusercontent.com/assets/239003/25209852/6d867902-254b-11e7-9b4a-57fff4af5552.png)

**Comment by 1st1** [comment] 2017-04-20 16:50
Turns out this is a new limitation of Atom 1.16 (see https://github.com/atom/atom/issues/14263). Closing this one as there's nothing we can do about it.

**Closed by 1st1** 2017-04-20 16:50 UTC
