### ISSUE TITLE
what kind of enhancements over the default vscode python extension ?

### ISSUE THREAD

**Issue by adrianmak** [MagicStack/MagicPython#61] opened 2016-10-15 04:14 UTC
I am using default python extension.

**Comment by elprans** [comment] 2016-10-17 13:38
VSCode 1.5 includes MagicPython by default.  You can still install MagicPython as an extension to be able to receive updates more frequently.

**Comment by 1st1** [comment] 2016-10-18 00:29
Closing as a dupe of #59

**Closed by 1st1** 2016-10-18 00:29 UTC
Labels: question
