### ISSUE TITLE
MagicPython not compatible with GitSavvy because of old syntax file?

### ISSUE THREAD

**Issue by reagle** [MagicStack/MagicPython#86] opened 2017-06-06 21:36 UTC
I use MagicPython and GitSavvy and noted that the syntax highlighting fails to work in some instances. @stoivo said at divmain/GitSavvy/pull/661

> The reason why magicpython isn't working because it uses the old version of sublime syntax files. MagicPython is using .tmLanguage while GitSavvy only checks for '.sublime-syntax`.
It is quite easy to fix for MagicPython if they want to. (You can create and issue)

**Comment by 1st1** [comment] 2017-06-06 21:38
> It is quite easy to fix for MagicPython if they want to. (You can create and issue)

Unfortunately is's not an "easy fix" for us. `.sublime-syntax` is a completely different format so it's not going to happen in the foreseeable future.

**Comment by reagle** [comment] 2017-06-06 21:40
Okay, thanks for the info.

**Comment by stoivo** [comment] 2017-06-07 08:59
I make a single PR to support newest syntax files.

**Comment by reagle** [comment] 2017-06-07 12:11
@stoivo thanks! I look forward to the PR being pulled and having this feature pushed to package control.

**Comment by reagle** [comment] 2017-06-08 10:32
@1st1 are you amendable to @stoivo's pull request? Or were you saying that because MagicPython supports Sublime Text, Atom, and Visual Studio Code you will not support .sublime-syntax?

**Comment by 1st1** [comment] 2017-06-08 22:09
> @1st1 are you amendable to @stoivo's pull request? 

We're discussing the details of the PR in the PR.

**Comment by 1st1** [comment] 2017-07-24 18:58
Seems that the issue is now resolved on the GitSavvy side. Closing the issue (feel free to re-open if needed).

**Closed by 1st1** 2017-07-24 18:58 UTC
