### ISSUE TITLE
MagicPython errs once a day when opening ST3

### ISSUE THREAD

**Issue by txtsd** [MagicStack/MagicPython#26] opened 2015-11-07 08:14 UTC
![Here's an image.](https://i.imgur.com/4uTy2uf.png) The graphical bug is because the theme is being reloaded.
Here's a log.
```
DPI scale: 1
startup, version: 3083 linux x64 channel: stable
executable: /opt/sublime_text_3/sublime_text
working dir: /
packages path: /home/txtsd/.config/sublime-text-3/Packages
state path: /home/txtsd/.config/sublime-text-3/Local
zip path: /opt/sublime_text_3/Packages
zip path: /home/txtsd/.config/sublime-text-3/Installed Packages
ignored_packages: ["Arduino-like IDE", "Colorcoder", "Djaneiro", "Emmet", "GoSublime", "isort", "nginx", "Perv - Color Scheme", "Python", "SublimeLinter", "SublimeLinter-javac", "Theme - Nexus", "Trimmer", "Vintage"]
pre session restore time: 2.68182
startup time: 3.18831
first paint time: 3.45688
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-ssl-linux
Package Control: Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
reloading plugin 0_package_control_loader.02-bz2
reloading plugin ColorPicker.sublimecp
reloading plugin FileDiffs.file_diffs
reloading plugin Git.add
reloading plugin Git.annotate
reloading plugin Git.commit
reloading plugin Git.diff
reloading plugin Git.flow
reloading plugin Git.git
reloading plugin Git.history
reloading plugin Git.repo
reloading plugin Git.stash
reloading plugin Git.status
reloading plugin Git.statusbar
reloading plugin HTML5.encode_html_entities
reloading plugin HTML5.html_completions
reloading plugin PKGBUILD.pkgbuildCommands
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.version
plugins loaded
Package Control: Installing 2 upgrades
ignored packages updated to: ["Arduino-like IDE", "Colorcoder", "Djaneiro", "Emmet", "GoSublime", "isort", "MagicPython", "nginx", "Perv - Color Scheme", "Python", "Seti_UI", "SublimeLinter", "SublimeLinter-javac", "Theme - Nexus", "Trimmer", "Vintage"]
error: Error loading syntax file "Packages/XML/XML.tmLanguage": Unable to open Packages/MagicPython/grammars/MagicPython.tmLanguage
reloading Packages/MagicPython/settings/sublime/MagicPython.sublime-settings
generating syntax summary
generating meta info summary
reloading Packages/Seti_UI/+res/Ext/CSS.sublime-settings
reloading Packages/Seti_UI/+res/Ext/HTML (Rails).sublime-settings
reloading Packages/Seti_UI/+res/Ext/HTML.sublime-settings
reloading Packages/Seti_UI/+res/Ext/Plain text.sublime-settings
reloading Packages/Seti_UI/+res/Ext/Ruby Haml.sublime-settings
reloading Packages/Seti_UI/+res/Ext/Ruby.sublime-settings
reloading Packages/Seti_UI/+res/Ext/SCSS.sublime-settings
reloading Packages/Seti_UI/+res/Ext/Sass.sublime-settings
reloading Packages/Seti_UI/Main/Widget - Seti_orig.sublime-settings
generating syntax summary
generating meta info summary
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
Package Control: Upgraded MagicPython to 0.4.44
ignored packages updated to: ["Arduino-like IDE", "Colorcoder", "Djaneiro", "Emmet", "GoSublime", "isort", "nginx", "Perv - Color Scheme", "Python", "Seti_UI", "SublimeLinter", "SublimeLinter-javac", "Theme - Nexus", "Trimmer", "Vintage"]
reloading Packages/MagicPython/settings/sublime/MagicPython.sublime-settings
generating syntax summary
generating meta info summary
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
reloading Packages/User/Preferences.sublime-settings
Package Control: Upgraded Seti_UI to 2015.11.06.16.14.56
ignored packages updated to: ["Arduino-like IDE", "Colorcoder", "Djaneiro", "Emmet", "GoSublime", "isort", "nginx", "Perv - Color Scheme", "Python", "SublimeLinter", "SublimeLinter-javac", "Theme - Nexus", "Trimmer", "Vintage"]
generating syntax summary
reloading Packages/Seti_UI/Main/Widget - Seti_orig.sublime-settings
generating meta info summary
reloading Packages/Seti_UI/+res/Ext/CSS.sublime-settings
reloading Packages/Seti_UI/+res/Ext/HTML (Rails).sublime-settings
reloading Packages/Seti_UI/+res/Ext/HTML.sublime-settings
reloading Packages/Seti_UI/+res/Ext/Plain text.sublime-settings
reloading Packages/Seti_UI/+res/Ext/Ruby Haml.sublime-settings
reloading Packages/Seti_UI/+res/Ext/Ruby.sublime-settings
reloading Packages/Seti_UI/+res/Ext/SCSS.sublime-settings
reloading Packages/Seti_UI/+res/Ext/Sass.sublime-settings
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
reloading Packages/User/Preferences.sublime-settings
ERROR:root:[Errno 111] Connection refused
ERROR:root:Traceback (most recent call last):
  File "/home/txtsd/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/worker.py", line 191, in start
    self.client = AsynClient(self.available_port)
  File "/home/txtsd/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/jsonclient.py", line 36, in __init__
    EventHandler.__init__(self, (host, port))
  File "/home/txtsd/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/ioloop.py", line 107, in __init__
    self.sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
```

This is what it looks like when it doesn't break.
```
DPI scale: 1
startup, version: 3083 linux x64 channel: stable
executable: /opt/sublime_text_3/sublime_text
working dir: /
packages path: /home/txtsd/.config/sublime-text-3/Packages
state path: /home/txtsd/.config/sublime-text-3/Local
zip path: /opt/sublime_text_3/Packages
zip path: /home/txtsd/.config/sublime-text-3/Installed Packages
ignored_packages: ["Arduino-like IDE", "Colorcoder", "Djaneiro", "Emmet", "GoSublime", "isort", "nginx", "Perv - Color Scheme", "Python", "SublimeLinter", "SublimeLinter-javac", "Theme - Nexus", "Trimmer", "Vintage"]
pre session restore time: 0.42951
startup time: 0.734251
first paint time: 0.792481
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-ssl-linux
Package Control: Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
reloading plugin 0_package_control_loader.02-bz2
reloading plugin ColorPicker.sublimecp
reloading plugin FileDiffs.file_diffs
reloading plugin Git.add
reloading plugin Git.annotate
reloading plugin Git.commit
reloading plugin Git.diff
reloading plugin Git.flow
reloading plugin Git.git
reloading plugin Git.history
reloading plugin Git.repo
reloading plugin Git.stash
reloading plugin Git.status
reloading plugin Git.statusbar
reloading plugin HTML5.encode_html_entities
reloading plugin HTML5.html_completions
reloading plugin PKGBUILD.pkgbuildCommands
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.version
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2015-11-07 13:36:27, next run at 2015-11-07 14:36:27 or after
```

**Comment by 1st1** [comment] 2015-11-07 08:25
Can't reproduce ;(
Does it highlight Python files correctly?  If you close all open files and reload ST, does it show the dialog?

**Comment by txtsd** [comment] 2015-11-07 08:44
I cannot pinpoint what causes it. It happens erratically. It doesn't happen every time I load ST3, so even if I close all files and reload, we won't get any useful information.
I think the highlighting only went away the first time it ever happened. It hasn't gone away on subsequent errors.

**Comment by txtsd** [comment] 2015-11-07 08:45
Ah there have been updates in the past week! Perhaps the upgrade process triggers it?

**Comment by 1st1** [comment] 2015-11-07 16:44
> Perhaps the upgrade process triggers it?

Maybe.  We've released a couple of new versions in the last few days.  

The thing is that if there was an error in the MagicPython grammar, ST would complain about it all the time.  So it might be some weird bug in ST that causes it to bark during the update process.

**Comment by txtsd** [comment] 2015-11-07 18:09
That's probably it. Should I change the title to say error on update, or should I wait to confirm it until the next update?

**Comment by 1st1** [comment] 2015-11-08 16:38
I've just pushed `v0.5.0`!

**Comment by txtsd** [comment] 2015-11-08 21:30
This time it upgraded without breaking!
What did you change though? There's nothing in the commit log between this and the previous version.

**Comment by 1st1** [comment] 2015-11-09 01:37
> What did you change though? 

Nothing - we planned to bump to 0.5 since long ago.  I think the errors you've seen in ST were caused by some bugs in package control or ST editor itself.  It seems that there is nothing here we can fix, so I'm closing the issue.  If you see something like that again, please feel free to reopen.

**Closed by 1st1** 2015-11-09 01:37 UTC
Labels: sublime editor bug

**Comment by txtsd** [comment] 2015-11-09 04:34
Possibly. Sounds good.

**Comment by txtsd** [comment] 2015-11-18 05:37
It happened again, and I didn't even have any tab using the MagicPython syntax. But it does happen during an upgrade!
Is there, perhaps, a way to point ST3 to use a temporary copy of the grammar file while the package is being updated, then point to the updated file?
I'm not sure why my Shellscript syntax broke though.
Also, can you reopen the issue until we can figure this out, please?
![Screenshot](https://i.imgur.com/3gVcNh8.png)
```
DPI scale: 1
startup, version: 3083 linux x64 channel: stable
executable: /opt/sublime_text_3/sublime_text
working dir: /
packages path: /home/txtsd/.config/sublime-text-3/Packages
state path: /home/txtsd/.config/sublime-text-3/Local
zip path: /opt/sublime_text_3/Packages
zip path: /home/txtsd/.config/sublime-text-3/Installed Packages
ignored_packages: ["Arduino-like IDE", "Colorcoder", "ColorPicker", "Djaneiro", "Emmet", "Git", "GoSublime", "isort", "nginx", "Perv - Color Scheme", "Python", "SublimeLinter", "SublimeLinter-javac", "Theme - Nexus", "Trimmer", "Vintage"]
pre session restore time: 0.263199
startup time: 0.543236
first paint time: 0.581456
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-ssl-linux
Package Control: Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
reloading plugin 0_package_control_loader.02-bz2
reloading plugin FileDiffs.file_diffs
reloading plugin HTML5.encode_html_entities
reloading plugin HTML5.html_completions
reloading plugin PKGBUILD.pkgbuildCommands
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.version
plugins loaded
Package Control: Installing 1 upgrades
ignored packages updated to: ["Arduino-like IDE", "Colorcoder", "ColorPicker", "Djaneiro", "Emmet", "Git", "GoSublime", "isort", "MagicPython", "nginx", "Perv - Color Scheme", "Python", "SublimeLinter", "SublimeLinter-javac", "Theme - Nexus", "Trimmer", "Vintage"]
error: Error loading syntax file "Packages/ShellScript/Shell-Unix-Generic.tmLanguage": Unable to open Packages/MagicPython/grammars/MagicPython.tmLanguage
reloading Packages/MagicPython/settings/sublime/MagicPython.sublime-settings
generating syntax summary
generating meta info summary
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
Package Control: Upgraded MagicPython to 0.5.1
ignored packages updated to: ["Arduino-like IDE", "Colorcoder", "ColorPicker", "Djaneiro", "Emmet", "Git", "GoSublime", "isort", "nginx", "Perv - Color Scheme", "Python", "SublimeLinter", "SublimeLinter-javac", "Theme - Nexus", "Trimmer", "Vintage"]
reloading Packages/MagicPython/settings/sublime/MagicPython.sublime-settings
generating syntax summary
generating meta info summary
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
reloading Packages/User/Preferences.sublime-settings
```

**Comment by 1st1** [comment] 2015-11-18 15:16
Well, in the log it looks like the error is caused by Shell-Unix-Generic.tmLanguage.  MagicPython reloaded without any errors.  Maybe it just triggers the reload (since its version has changed), but the broken syntax belongs to some other package?

> Is there, perhaps, a way to point ST3 to use a temporary copy of the grammar file while the package is being updated, then point to the updated file?

I don't think it's possible ;(

**Comment by txtsd** [comment] 2015-11-18 16:17
Shell-Unix-Generic.tmLanguage is included in ST3 by default.
Not sure why these syntaxes are breaking ever since I installed MagicPython.

**Comment by 1st1** [comment] 2015-11-18 16:43
I'm honestly not sure what to do here. I'd love to help, but I can't reproduce this on my machine.

**Comment by 1st1** [comment] 2015-11-18 18:03
@txtsd We've pushed a new version - 0.5.2.  There are some tweaks there, maybe this issue will be resolved.

**Comment by txtsd** [comment] 2015-11-19 02:04
Exactly the same error as the last one. I think we should just let this be until we have a way of finding out more about this issue.
