### ISSUE TITLE
Return type for python method will mess up the color scheme for the python code

### ISSUE THREAD

**Issue by jtony001** [MagicStack/MagicPython#169] opened 2018-12-04 08:54 UTC
* **Editor name and version**: VSCODE 1.29.1 
* **Platform**: MacOs High Sierra
* **Color scheme**:
* **MagicPython version**:1.1.10
* **A sreenshot**:
![screen shot 2018-12-04 at 2 22 37 pm](https://user-images.githubusercontent.com/22070334/49430091-1efdae00-f7d0-11e8-938f-9494ba46a2b8.png)

* **5-10 lines of surrounding code**:
"""Module  doc"""

import time

def method1(cat: str)-> dict:
    """
        some doc string
    """
    cat_dict = {}
    req_ts = time.time()
    return cat_dict

def method2(n):
    """
	Some doc string
	"""
    pass

**Comment by elprans** [comment] 2018-12-04 14:19
You have the “Python for VSCode” extension installed, which overrides the grammar.

Duplicate of #162 and #168.

**Closed by elprans** 2018-12-04 14:19 UTC
