### ISSUE TITLE
Not all keywords and built-in functions are highlighted.

### ISSUE THREAD

**Issue by MikeYaco** [MagicStack/MagicPython#38] opened 2016-04-22 21:54 UTC
As the title says, not all keywords and built-in functions are highlighted.

For instance,

![image](https://cloud.githubusercontent.com/assets/6750444/14755859/ccac92f4-08aa-11e6-9584-5bd1da53bdf6.png)

neither 'in' nor 'enumerate' have any syntax highlighting.

**Comment by 1st1** [comment] 2016-04-22 21:57
What's the editor/version and the color schema?

**Comment by diwu1989** [comment] 2016-04-24 16:29
im seeing the same issue, using latest dev channel ST3
other keywords like `not and or` aren't being highlighted

**Comment by MikeYaco** [comment] 2016-04-25 17:33
Version: 1.0.0
Color Theme: Dark+ (default dark)

Playing around with color themes, I noticed they all have different behaviors for what works and what doesn't.

I have changed my Color theme to Monokai. That seems to work.

**Comment by 1st1** [comment] 2016-04-25 17:44
> Playing around with color themes, I noticed they all have different behaviors for what works and what doesn't.

Yeah, that's what I thought.  Anyways, what's the name of the color scheme that fails to highlight correctly?  BTW, you can also try [Chromodynamics](https://github.com/MagicStack/Chromodynamics) -- that's the color scheme I use with MagicPython.

**Comment by MikeYaco** [comment] 2016-04-25 17:53
> Color Theme: Dark+ (default dark)

**Comment by 1st1** [comment] 2016-04-25 21:41
> Version: 1.0.0

Is that Atom?  That's a **very** old version of Atom...

**Comment by MikeYaco** [comment] 2016-04-25 21:42
Oh, whoops should have specified what text editor. VS Code

**Comment by 1st1** [comment] 2016-04-25 21:56
Yep, I just verified -- it's a problem of that specific color theme in VSCode. Judging by its source code, Dark+ is extremely limited, I'd recommend to simply find another theme.

@diwu1989 I'm using ST3 build 3111. Can't reproduce this.  I believe your problem is similar -- buggy color theme.

**Comment by 1st1** [comment] 2016-05-05 17:46
Closing this issue.

**Closed by 1st1** 2016-05-05 17:46 UTC
